"""deleted content_html

Revision ID: 6a130ec10759
Revises: 8754d83d7e12
Create Date: 2024-04-08 15:51:42.786896

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6a130ec10759"
down_revision: Union[str, None] = "8754d83d7e12"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("articles", "content_html")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("articles", sa.Column("content_html", sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
